services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: "host"
    volumes:
      - ..:/workspace:cached    # project files
    command: sleep infinity

