kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # - containerPort: 5000
  #   hostPort: 5000
  #   protocol: TCP
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
- role: worker
- role: worker 